version: 2.1

jobs:
  # INSTALL DEPENDENCIES
  "build yarn cache":
    working_directory: ~
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  # Builds the image and publishes it to the docker repo
  "build image":
    working_directory: ~
    docker:
      - image: circleci/node:latest
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build application
          command: yarn build
      - run:
          name: Docker Image - Build and Push to Quay
          command: docker build  -f ./Dockerfile  .

workflows:
  version: 2
  build:
    jobs:
      - "build yarn cache"
      - "build image":
          requires:
            - "build yarn cache"